<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tabt_sync_form_tabt_settings_form_alter(array &$form): void {
  $form['truncate'] = [
    '#type' => 'checkbox',
    '#title' => t('Clear existing data'),
  ];

  $form['#submit'][] = function (array &$form, FormStateInterface $form_state): void {
    if ($form_state->getValue('truncate')) {
      Drupal::service('tabt_sync.syncer')->truncateAll();
    }
  };
}

/**
 * Implements hook_views_data().
 */
function tabt_sync_views_data(): array {
  $data['views']['tabt_sync'] = [
    'title' => t('TabT sync'),
    'area' => ['id' => 'tabt_sync'],
  ];

  return $data;
}
